# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main -buildvcs=false ."
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  follow_symlink = true
  poll = true

[log]
  time = true
